channel_name = {
  "k4sen": "UChUjERVG8eKEAJSCef-tTmg",
  "かせん": "UChUjERVG8eKEAJSCef-tTmg",
  "かせんさん": "UChUjERVG8eKEAJSCef-tTmg",
  "k4senさん": "UChUjERVG8eKEAJSCef-tTmg",
  "ニキ": "UChUjERVG8eKEAJSCef-tTmg",
  "釈迦": "UCjg5-lUiUzdmzzBRY9Xqrhw",
  "釈迦さん": "UCjg5-lUiUzdmzzBRY9Xqrhw",
  "しゃか": "UCjg5-lUiUzdmzzBRY9Xqrhw",
  "しゃかさん": "UCjg5-lUiUzdmzzBRY9Xqrhw",
  "shaka": "UCjg5-lUiUzdmzzBRY9Xqrhw",
  "shakaさん": "UCjg5-lUiUzdmzzBRY9Xqrhw",
  "関優太": "UC2j4lymo8Ce_1RXMeo4afcQ",
  "関さん": "UC2j4lymo8Ce_1RXMeo4afcQ",
  "スタヌ": "UC2j4lymo8Ce_1RXMeo4afcQ",
  "シナモン": "UCoACtIo4BxcvFBpOyF4WclA",
  "加藤純一": "UCx1nAvtVDIsaGmCMSe8ofsQ",
  "うんこちゃん": "UCH-lygWpHodDff3iQurnWnQ",
  "KH": "UCMEI4RcffOJZUuYIVcim8Zw",
  "KHさん": "UCMEI4RcffOJZUuYIVcim8Zw",
  "kh": "UCMEI4RcffOJZUuYIVcim8Zw",
  "khさん": "UCMEI4RcffOJZUuYIVcim8Zw",
  "らいじん": "UCvXYV_0wzcxMnH_J4HCZxBw",
  "らいじんさん": "UCvXYV_0wzcxMnH_J4HCZxBw",
  "スパイギア": "UCBnFEiB9v4afsg8tbhmIACQ",
  "ギアさん": "UCBnFEiB9v4afsg8tbhmIACQ",
  "k4senサブ": "UC_y7OIzEJAeYJ_ypYJKPVaA",
  "k4sen切り抜き": "UC_y7OIzEJAeYJ_ypYJKPVaA",
  "サブシーン": "UC_y7OIzEJAeYJ_ypYJKPVaA",
  "うるか": "UChrTMfNcD1eN2ENGWBD7lUQ",
  "うるーか": "UChrTMfNcD1eN2ENGWBD7lUQ",
  "けんき": "UCNicQVuAQJYlCQKEw1TKn1A",
  "けんきさん": "UCNicQVuAQJYlCQKEw1TKn1A",
  "おぼ": "UCE4jlsAFvREH-pRd55F8jSA",
  "もこう": "UCENoC6MLc4pL-vehJyzSWmg",
  "ななひら": "UC_fYA9QRK-aJnFTgvR_4zug",
  "鈴木ノリアキ": "UC5z1TSPQsDeAWiA8AksvK3A",
  "ノリアキ": "UC5z1TSPQsDeAWiA8AksvK3A",
  "藍月なくる": "UCQHCHIoeu0FRJTJNMG2_Ezw",
  "なくちゃ": "UCQHCHIoeu0FRJTJNMG2_Ezw",
  "夜よいち": "UCqRkLD5OCNq37AAtxStmm3A",
  "よいち": "UCqRkLD5OCNq37AAtxStmm3A",
  "よいっち": "UCqRkLD5OCNq37AAtxStmm3A",
  "ボドカ": "UCIYaPLvP0y2LbSYk7QbRSmQ",
  "VDK": "UCIYaPLvP0y2LbSYk7QbRSmQ",
  "vdk": "UCIYaPLvP0y2LbSYk7QbRSmQ",
  "ジェラードン": "UCRaaCxSF8nEpfG3ZHesXKxw",
  "わしゃがなTV": "UCReBAqqC-hc9d70gOftfitg",
  "わしゃがな": "UCReBAqqC-hc9d70gOftfitg",

}



support_channel ={
    "k4sen",
    "sub scene(k4sen切り抜き)",
    "釈迦",
    "関優太",
    "シナモン",
    "加藤純一",
    "うんこちゃん（切り抜き）",
    "KH",
    "らいじん",
    "スパイギア",
    "うるか",
    "けんき",
    "おぼ",
    "夜よいち",
    "ボドカ",
    "もこう",
    "ななひら",
    "鈴木ノリアキ",
    "藍月なくる",
    "ジェラードン",
    "わしゃがなTV",
    
}